### ISSUE TITLE
21cmfast_env.yml, line with pip install keeps crashing

### ISSUE THREAD

**Issue by pelmini** [HERA-Team/CHAMP_Bootcamp#2]
Conda cant make the 21cmfast environment from the .yml file as its throwing a parser error.
<img width="945" alt="Screen Shot 2021-07-02 at 1 14 12 PM" src="https://user-images.githubusercontent.com/37095187/124324238-7787ba00-db37-11eb-9077-84eddb716fde.png">

**Comment by steven-murray** [comment]
ah! I'll fix it up.

**Comment by steven-murray** [comment]
Should be fixed in https://github.com/HERA-Team/CHAMP_Bootcamp/commit/80be00f24372fb11d3bb27565ed16195d3599ea0
